return {
  termguicolors = true,
  laststatus = 2,
  cursorline = false,
  number = true,
  visualbell = true,
  expandtab = false,
  colorcolumn = "100",
  tabstop = 4,
  shiftwidth = 0,
  autoindent = true,
  cindent = true,
  timeoutlen = 300,
  updatetime = 100,
  showmode = false,
}
